### ISSUE TITLE
error on 14.0

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/EffectSpleef#1]
getSpawn is not working?

**Comment by inxomnyaa** [comment]
You didn't read the readme.

The spawn is the world spawn

**Comment by ghost** [comment]
Its working on 13.1 i think its version 14.0 fault

**Comment by inxomnyaa** [comment]
I use the plugin on my 0.14 server

**Comment by ghost** [comment]
Im using windows installer by deibo

**Comment by inxomnyaa** [comment]
That shouldnt matter.. but i guess (because you said installer and deibo, which means you use pocketmine) its a php7 issue. i will check it.. any crash dumps?

**Comment by ghost** [comment]
Okay i think its php7 issue . because i cant setworldspawn xD

**Comment by ghost** [comment]
I tried this and it works

LeaveLobby 
$sender->teleport($sender->getServer()->getDefaultLevel()->getSafeSpawn(), 0, 0);

RespawnPlayer
$player->teleport($player->getLevel()->getSafeSpawn());

**Comment by inxomnyaa** [comment]
I actually think setworldspawn is an essentialspe feature.

Thanks for the code, i'll implement that. Havent got this idea.

**Comment by inxomnyaa** [comment]
Outdated issue - Flagged as fixed
