### ISSUE TITLE
Error: ord() expects parameter 1 to be string, boolean given

### ISSUE THREAD

**Issue by HiggsInc** [thebigsmileXD/EffectSpleef#3]
Hey @thebigsmileXD, could you advise on the following error?

I had just finished with setting spawn points and was about to /spleef join which then produced the error.

[CrashDump](http://pastebin.com/DRpNSYeq)

Error: ord() expects parameter 1 to be string, boolean given
File: /src/pocketmine/level/format/io/region/RegionLoader
Line: 95
Type: notice

Code:
[86] 
[87] 		$this->lastUsed = time();
[88] 
[89] 		if(!$this->isChunkGenerated($index)){
[90] 			return null;
[91] 		}
[92] 
[93] 		fseek($this->filePointer, $this->locationTable[$index][0] << 12);
[94] 		$length = Binary::readInt(fread($this->filePointer, 4));
[95] 		$compression = ord(fgetc($this->filePointer));
[96] 
[97] 		if($length <= 0 or $length > self::MAX_SECTOR_LENGTH){ //Not yet generated / corrupted
[98] 			if($length >= self::MAX_SECTOR_LENGTH){
[99] 				$this->locationTable[$index][0] = ++$this->lastSector;
[100] 				$this->locationTable[$index][1] = 1;
[101] 				MainLogger::getLogger()->error("Corrupted chunk header detected");
[102] 			}
[103] 			return null;
[104] 		}
[105] 

Backtrace:
#0 /src/pocketmine/level/format/io/region/McRegion(341): pocketmine\level\format\io\region\RegionLoader->readChunk(integer 12, integer 25)
#1 /src/pocketmine/level/format/io/region/McRegion(289): pocketmine\level\format\io\region\McRegion->loadChunk(integer 12, integer 25, boolean )
#2 /src/pocketmine/level/Level(2433): pocketmine\level\format\io\region\McRegion->getChunk(integer 12, integer 25, boolean )
#3 /src/pocketmine/level/Level(2119): pocketmine\level\Level->loadChunk(integer 12, integer 25, boolean )
#4 /src/pocketmine/level/generator/PopulationTask(57): pocketmine\level\Level->getChunk(integer 12, integer 25, boolean )
#5 /src/pocketmine/level/Level(2709): pocketmine\level\generator\PopulationTask->__construct(pocketmine\level\Level object, pocketmine\level\format\Chunk object)
#6 /src/pocketmine/Player(781): pocketmine\level\Level->populateChunk(integer 13, integer 24)
#7 /src/pocketmine/Player(1630): pocketmine\Player->sendNextChunk(boolean)
#8 /src/pocketmine/Server(2364): pocketmine\Player->checkNetwork(boolean)
#9 /src/pocketmine/Server(2121): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2003): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(1624): pocketmine\Server->start(boolean)
#12 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Admin\Software\MCPE\Software\clearsky\, string C:\Users\Admin\Software\MCPE\Software\clearsky\, string C:\Users\Admin\Software\MCPE\Software\clearsky\plugins\)

PocketMine-MP version: 1.6.2dev #0 [Protocol 102; API 3.0.0-ALPHA4]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT  10.0 build 14393 (Windows 10) AMD64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

**Comment by inxomnyaa** [comment]
Looks more like an region error
```File: /src/pocketmine/level/format/io/region/RegionLoader```
some error in the world?

Good issue btw! Haven't seen such good issue reportings in ages

**Comment by inxomnyaa** [comment]
Outdated issue - Flagged as fixed (was pmmp issue)
